create table public.access_audit_events (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('invited', 'revoked')),
  actor_user_id uuid not null,
  target_user_id uuid not null,
  target_email text not null,
  created_at timestamptz not null default now()
);

alter table public.access_audit_events enable row level security;
revoke all on table public.access_audit_events from anon, authenticated;

-- The service role performs the server-only administration and audit writes.
-- It bypasses RLS but still needs explicit privileges with this project's
-- non-default grant configuration.
grant select, insert on table public.access_audit_events to service_role;
grant usage, select on sequence public.access_audit_events_id_seq to service_role;
