create type public.app_role as enum ('operator', 'admin');

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role public.app_role not null default 'operator',
  created_at timestamptz not null default now()
);

create table public.exams (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  mnemonic text not null check (btrim(mnemonic) <> ''),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, mnemonic),
  unique (mnemonic)
);

create table public.exam_aliases (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  alias text not null check (btrim(alias) <> ''),
  normalized_alias text not null check (btrim(normalized_alias) <> ''),
  created_at timestamptz not null default now(),
  unique (exam_id, normalized_alias)
);

create index exam_aliases_normalized_alias_idx
  on public.exam_aliases (normalized_alias);

create table public.exam_compositions (
  package_exam_id bigint not null references public.exams(id) on delete cascade,
  component_exam_id bigint not null references public.exams(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (package_exam_id, component_exam_id),
  check (package_exam_id <> component_exam_id)
);

create function private.create_user_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, display_name, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1)),
    case
      when new.raw_app_meta_data ->> 'role' = 'admin' then 'admin'::public.app_role
      else 'operator'::public.app_role
    end
  )
  on conflict (user_id) do update
  set display_name = excluded.display_name,
      role = excluded.role;
  return new;
end;
$$;

revoke all on function private.create_user_profile() from public, anon, authenticated;

create function private.is_admin()
returns boolean
language sql
stable
set search_path = ''
as $$
  select coalesce(((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin', false)
$$;

revoke all on function private.is_admin() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

create trigger create_profile_after_auth_user
after insert or update of raw_app_meta_data on auth.users
for each row execute function private.create_user_profile();

alter table public.profiles enable row level security;
alter table public.exams enable row level security;
alter table public.exam_aliases enable row level security;
alter table public.exam_compositions enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.exams from anon, authenticated;
revoke all on table public.exam_aliases from anon, authenticated;
revoke all on table public.exam_compositions from anon, authenticated;

grant select on table public.profiles to authenticated;
grant select, insert, update, delete on table public.exams to authenticated;
grant select, insert, update, delete on table public.exam_aliases to authenticated;
grant select, insert, update, delete on table public.exam_compositions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "authenticated users read their own profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = user_id);

create policy "authenticated users read exams"
on public.exams for select to authenticated
using ((select auth.uid()) is not null);

create policy "administrators insert exams"
on public.exams for insert to authenticated
with check ((select private.is_admin()));

create policy "administrators update exams"
on public.exams for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "administrators delete exams"
on public.exams for delete to authenticated
using ((select private.is_admin()));

create policy "authenticated users read exam aliases"
on public.exam_aliases for select to authenticated
using ((select auth.uid()) is not null);

create policy "administrators insert exam aliases"
on public.exam_aliases for insert to authenticated
with check ((select private.is_admin()));

create policy "administrators update exam aliases"
on public.exam_aliases for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "administrators delete exam aliases"
on public.exam_aliases for delete to authenticated
using ((select private.is_admin()));

create policy "authenticated users read exam compositions"
on public.exam_compositions for select to authenticated
using ((select auth.uid()) is not null);

create policy "administrators insert exam compositions"
on public.exam_compositions for insert to authenticated
with check ((select private.is_admin()));

create policy "administrators update exam compositions"
on public.exam_compositions for update to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

create policy "administrators delete exam compositions"
on public.exam_compositions for delete to authenticated
using ((select private.is_admin()));
